pipeline {
    agent any
    stages {
        stage("Run Script"){
            steps {
                dir("Task2") {
                    sh "sh deploy.sh"
                }
            }
        }
    }
}